graphhopper:
  datareader.file: sweden/source/sweden-latest.osm.pbf
  gtfs.file: sweden/source/sweden.gtfs.zip
  graph.location: sweden/graphhopper-release

  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest
    - name: car
      vehicle: car
      weighting: fastest
    - name: bike
      vehicle: bike
      weighting: fastest

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost
