graphhopper:
  datareader.file: sweden/source/sweden-latest.osm.pbf
  gtfs.file: sweden/source/sweden.gtfs.zip
  graph.location: sweden/sweden-with-transit

  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost
