graphhopper:
  datareader.file: sweden/source/sweden-latest.osm.pbf
  graph.location: sweden/graphhopper-dev

  profiles:
    - name: car
      vehicle: car
      weighting: fastest

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 8990
      bind_host: localhost
